package com.lm.domain.gen2;
// Generated Nov 29, 2015 3:16:23 PM by Hibernate Tools 4.3.1.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BookType generated by hbm2java
 */
@Entity
@Table(name="BookType"
    ,catalog="chorus"
)
public class BookType  implements java.io.Serializable {


     private int bookTypeId;
     private String name;

    public BookType() {
    }

	
    public BookType(int bookTypeId) {
        this.bookTypeId = bookTypeId;
    }
    public BookType(int bookTypeId, String name) {
       this.bookTypeId = bookTypeId;
       this.name = name;
    }
   
     @Id 

    
    @Column(name="bookTypeId", unique=true, nullable=false)
    public int getBookTypeId() {
        return this.bookTypeId;
    }
    
    public void setBookTypeId(int bookTypeId) {
        this.bookTypeId = bookTypeId;
    }

    
    @Column(name="name", length=200)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


